#!python
import os
Import('cbenv')

## project includes
cbenv.Append(CPPPATH=[Dir("./")])
cbenv.Append(CPPPATH=[Dir("var.h/")])

## core env
env_core = cbenv.Clone()
env_core.SOURCES = [

    Glob('*.cpp'),
    File('var.h/var.cpp'),
    File('var.h/_native.cpp'),
    Glob('error/*.cpp'),
    Glob('builtin/*.cpp'),

    Glob('tokenizer/*.cpp'),
    Glob('parser/*.cpp'),
    Glob('analyzer/*.cpp'),
    Glob('codegen/*.cpp'),

]

##Export('env_core')
##SConscript('parser/SConstruct')

cbenv.SOURCES += env_core.SOURCES