#!python
import os
Import('cbenv')

## project includes
cbenv.Append(CPPPATH=[Dir("./")])
cbenv.Append(CPPPATH=[Dir("var/")])

## core env
env_core = cbenv.Clone()
env_core.SOURCES = [

    Glob('*.cpp'),
    Glob('var/*.cpp'),
    Glob('error/*.cpp'),
    Glob('builtin/*.cpp'),
    Glob('binary/*.cpp'),

    Glob('tokenizer/*.cpp'),
    Glob('parser/*.cpp'),
    Glob('analyzer/*.cpp'),
    Glob('analyzer/expression/*.cpp'),
    Glob('codegen/*.cpp'),
    Glob('vm/*.cpp'),

]

##Export('env_core')
##SConscript('parser/SConstruct')

cbenv.SOURCES += env_core.SOURCES