#!python
import os
Import('cbenv')

# project includes
cbenv.add_include_dir('var.h')
cbenv.add_include_dir('.')

# core env
env_core = cbenv.Clone()
env_core.Append(CPPDEFINES=[]) # predefined macros
env_core.Append(CPPPATH=[])    # include files
env_core.Append(LIBPATH=[])    # static lib dir
env_core.Append(LIBS=[])       # static libs
env_core.sources = []         # source files

# collect obj files
env_core.sources += [
    'var.h/var.cpp',
    Glob('*.cpp'),
]
Export('env_core')
SConscript('parser/SConstruct')

for src in env_core.sources:
    cbenv.add_ide_sources(src)

# make library
lib = env_core.StaticLibrary(
        'bin/' + 'core' + env_core['out_suffix'], 
        env_core.sources
    )
cbenv.Prepend(LIBS=[lib])