#!python
import os, subprocess
Import('cbenv')

## project includes
#cbenv.Append(CPPPATH=[Dir("./")])

## os env
env_os = cbenv.Clone()
env_os.SOURCES = []

## source files
Export('env_os')
SConscript('%s/SConstruct'%env_os['platform']) ## windows, x11, osx

cbenv.SOURCES += env_os.SOURCES
