#!python
import os
Import('env')

## project includes
env.Append(CPPPATH=[Dir("./")])

SOURCES = [

    Glob('*.cpp'),
    Glob('types/*.cpp'),
    Glob('binary/*.cpp'),
    Glob('tokenizer/*.cpp'),
    Glob('parser/*.cpp'),
    Glob('analyzer/*.cpp'),
    Glob('analyzer/expression/*.cpp'),
    Glob('codegen/*.cpp'),
    Glob('compiler/*.cpp'),
    Glob('debugger/*.cpp'),
    Glob('vm/*.cpp'),
]

env.LIBS['cb_compiler'] += SOURCES