#!python
import os, subprocess
Import('env_os')

# project includes
env_os.add_include_dir('.')
env_os.add_lib('dl')

# windows env
env_os.Append(CPPDEFINES=[]) # predefined macros
sources = [                  # source files
    #'crash_handler_x11.cpp',
    Glob('*.cpp')
]

# compie list
for file in sources:
    obj = env_os.Object(file)
    env_os.source.append(obj)
