#!python
import os, subprocess
Import('env_os')

# project includes
env_os.add_include_dir('.')
env_os.add_lib('psapi')
env_os.add_lib('dbghelp')

# windows env
env_os.Append(CPPDEFINES=[]) # predefined macros
env_os.sources += [          # source files
    Glob('*.cpp'),
]

## this will compile to obj file and append
## for file in sources:
##     obj = env_os.Object(file)
##     env_os.sources.append(obj)