#!python
import os, subprocess
Import('env_os')
Import('cbenv')

## project includes
cbenv.Append(LIBS=['psapi', 'dbghelp'])
env_os.Append(CPPDEFINES=[])

## windows env
env_os.SOURCES += [
    Glob('*.cpp'),
]
